pipeline {
    agent any
    options{
      timestamps()
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            options{
              timeout(time: 60, unit:'MINUTES')
            }
            steps {
                parallel (
                    'task1': {
                        echo 'Parallel Task1'
                        sh './jenkins/scripts/test.sh'
                    },
                    'task2': {
                        echo 'Parallel Task1'
                    }
                )
            }
        }
        parallel(
            stage('Deliver for development') {
                steps {
                    sh './jenkins/scripts/deliver-for-development.sh'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    sh './jenkins/scripts/kill.sh'
                }
            }
            stage('Deploy for production') {
                when {
                    branch 'production'
                }
                steps {
                    sh './jenkins/scripts/deploy-for-production.sh'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    sh './jenkins/scripts/kill.sh'
                }
            }
        )
    }

    post{
      success {
        echo 'deploy successfully'
        mail to: 'huangyan.316@163.com',
             subject: "Successful Pipeline: ${currentBuild.fullDisplayName}",
             body: "Deploy successfully with ${env.BUILD_URL}"
      }
      failure {
        echo 'deploy failed'
        mail to: 'huangyan.316@163.com',
             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
             body: "Something is wrong with ${env.BUILD_URL}"
      }
    }
}
